### ISSUE TITLE
Breaks on Internet Explorer 11 on Windows 7 & Firefox 44.0.2 on Ubuntu 14.0.4

### ISSUE THREAD

**Issue by madsithlord** [kriasoft/react-starter-kit#1098]
Master branch breaks on Windows 7 (IE) & Ubuntu (Firefox ) machines. I used yarn to install and start the server.

Windows 7: 
Internet Explorer - 11 
Error: Objects are not valid as a React Child (found: object with keys{$$typeof, type, ref, props, _owner, _store}).
![issue screenshot](https://cloud.githubusercontent.com/assets/24827723/22277948/aba8f79e-e2e5-11e6-816c-4ff8500ff2b1.jpg)

Ubuntu 14.0.4:
Firefox 44.0.2 but works fine 48(Tried in a different Ubuntu 14.0.4)
![screenshot_from_firefox](https://cloud.githubusercontent.com/assets/24827723/22277957/b68801b4-e2e5-11e6-8b53-c08bc70fe797.png)

Any help would be really appreciated.

**Comment by danjambur** [comment]
Can't provide much feedback without a snippet of the code it's failing on unfortunately.

**Comment by frenzzy** [comment]
I think the problem is that polyfils are executed too late. This should be fixed in master branch.

**Comment by madsithlord** [comment]
@frenzzy , I am still trying to fix it but no luck. It would be really great if you could help me out. Thanks in advance.

**Comment by frenzzy** [comment]
Remove `import 'babel-polyfill';` from `src/client.js` and `src/server.js`
and add it to `tools/webpack.config.js` like so:
```js
// ...
  entry: {
    client: ['babel-polyfill', './src/client.js'],
  },
// ...
  entry: {
    server: ['babel-polyfill', './src/server.js'],
  },
// ...
```

**Comment by adamantium169** [comment]
I think the problem is with react-optimize, as commenting that out also fixes it, but inserting the babel-polyfill before it fixes it.

Add `'babel-polyfill',` in `tools/webpack.config.js` on line 61, before `'stage-2',` and it now seems to work in IE11.

**Comment by madsithlord** [comment]
@frenzzy & @adamantium169 , thank you for your solution. Just cloned the main branch and and followed @adamantium169's solution. Now it works fine on Internet Explorer 11 but I am still having the same issue on Firefox 44.0.2 on Ubuntu 14.0.4. Here I am copying the errors from Console

GET 
https://reactjsnews.com/img/playing-with-react-and-d3/basic_render.png [HTTP/2.0 403 Forbidden 224ms]
GET 
https://reactjsnews.com/img/playing-with-react-and-d3/plot_points.png [HTTP/2.0 403 Forbidden 223ms]
GET 
https://reactjsnews.com/img/playing-with-react-and-d3/complete_chart.png [HTTP/2.0 403 Forbidden 279ms]
GET 
https://reactjsnews.com/img/10x-react-performance/performance-benchmark-2.png [HTTP/2.0 403 Forbidden 280ms]
"Download the React DevTools for a better development experience: https://fb.me/react-devtools" vendor.js:29517:9
Warning: Failed prop type: The prop `children` is marked as required in `App`, but its value is `undefined`.
    in App (at client.js:124) vendor.js:936:9

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <!-- react-empty: 1 -
 (server) <div data-reactroot=" vendor.js:936:9

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vendor.js:15416:3
Unhandled promise rejection Invariant Violation: React.Children.only expected to receive a single React element child.
Stack trace:
invariant@http://localhost:3001/assets/vendor.js:883:15
onlyChild@http://localhost:3001/assets/vendor.js:42397:52
render@http://localhost:3001/assets/client.js:1001:14
proxiedMethod@http://localhost:3001/assets/vendor.js:36806:16
ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext/renderedElement<@http://localhost:3001/assets/vendor.js:29333:16
measureLifeCyclePerf@http://localhost:3001/assets/vendor.js:28612:12
ReactCompositeComponent._renderValidatedComponentWithoutOwnerOrContext@http://localhost:3001/assets/vendor.js:29332:25
ReactCompositeComponent._renderValidatedComponent@http://localhost:3001/assets/vendor.js:29359:27
ReactCompositeComponent.performInitialMount@http://localhost:3001/assets/vendor.js:28899:1
ReactCompositeComponent.mountComponent@http://localhost:3001/assets/vendor.js:28795:16
ReactReconciler.mountComponent@http://localhost:3001/assets/vendor.js:5084:18
ReactCompositeComponent.performInitialMount@http://localhost:3001/assets/vendor.js:28908:18
ReactCompositeComponent.mountComponent@http://localhost:3001/assets/vendor.js:28795:16
ReactReconciler.mountComponent@http://localhost:3001/assets/vendor.js:5084:18
mountComponentIntoNode@http://localhost:3001/assets/vendor.js:14269:16
TransactionImpl.perform@http://localhost:3001/assets/vendor.js:7618:13
batchedMountComponentIntoNode@http://localhost:3001/assets/vendor.js:14291:3
TransactionImpl.perform@http://localhost:3001/assets/vendor.js:7618:13
ReactDefaultBatchingStrategy.batchedUpdates@http://localhost:3001/assets/vendor.js:32526:14
batchedUpdates@http://localhost:3001/assets/vendor.js:2672:10
ReactMount._renderNewRootComponent@http://localhost:3001/assets/vendor.js:14485:5
ReactMount._renderSubtreeIntoContainer@http://localhost:3001/assets/vendor.js:14566:21
ReactMount.render@http://localhost:3001/assets/vendor.js:14587:12
_callee$@http://localhost:3001/assets/client.js:677:37
tryCatch@http://localhost:3001/assets/vendor.js:16521:37
invoke@http://localhost:3001/assets/vendor.js:16812:22
defineIteratorMethods/</prototype[method]@http://localhost:3001/assets/vendor.js:16573:16
tryCatch@http://localhost:3001/assets/vendor.js:16521:37
invoke@http://localhost:3001/assets/vendor.js:16754:24
defineIteratorMethods/</prototype[method]@http://localhost:3001/assets/vendor.js:16573:16
step@http://localhost:3001/assets/client.js:757:183
step/<@http://localhost:3001/assets/client.js:757:361
notify/</run@http://localhost:3001/assets/vendor.js:21187:22
notify/<@http://localhost:3001/assets/vendor.js:21200:28
module.exports/flush@http://localhost:3001/assets/vendor.js:8729:9
 vendor.js:21217:11

[HMR] connected vendor.js:17324:22
Unhandled promise rejection TypeError: value.route is undefined
Stack trace:
_callee$@http://localhost:3001/assets/vendor.js:43687:21
tryCatch@http://localhost:3001/assets/vendor.js:16521:37
invoke@http://localhost:3001/assets/vendor.js:16812:22
defineIteratorMethods/</prototype[method]@http://localhost:3001/assets/vendor.js:16573:16
step@http://localhost:3001/assets/vendor.js:17811:22
exports.default/</<@http://localhost:3001/assets/vendor.js:17829:14
Promise@http://localhost:3001/assets/vendor.js:19238:7
exports.default/<@http://localhost:3001/assets/vendor.js:17808:1
next@http://localhost:3001/assets/vendor.js:43715:16
_callee$@http://localhost:3001/assets/client.js:167:1
tryCatch@http://localhost:3001/assets/vendor.js:16521:37
invoke@http://localhost:3001/assets/vendor.js:16812:22
defineIteratorMethods/</prototype[method]@http://localhost:3001/assets/vendor.js:16573:16
step@http://localhost:3001/assets/client.js:144:183
_asyncToGenerator/</<@http://localhost:3001/assets/client.js:144:437
Promise@http://localhost:3001/assets/vendor.js:21291:7
_asyncToGenerator/<@http://localhost:3001/assets/client.js:144:99
action@http://localhost:3001/assets/client.js:160:12
_callee$@http://localhost:3001/assets/vendor.js:43694:1
tryCatch@http://localhost:3001/assets/vendor.js:16521:37
invoke@http://localhost:3001/assets/vendor.js:16812:22
defineIteratorMethods/</prototype[method]@http://localhost:3001/assets/vendor.js:16573:16
step@http://localhost:3001/assets/vendor.js:17811:22
exports.default/</<@http://localhost:3001/assets/vendor.js:17829:14
Promise@http://localhost:3001/assets/vendor.js:19238:7
exports.default/<@http://localhost:3001/assets/vendor.js:17808:1
next@http://localhost:3001/assets/vendor.js:43715:16
_callee2$@http://localhost:3001/assets/vendor.js:43735:1
tryCatch@http://localhost:3001/assets/vendor.js:16521:37
invoke@http://localhost:3001/assets/vendor.js:16812:22
defineIteratorMethods/</prototype[method]@http://localhost:3001/assets/vendor.js:16573:16
step@http://localhost:3001/assets/vendor.js:17811:22
exports.default/</<@http://localhost:3001/assets/vendor.js:17829:14
Promise@http://localhost:3001/assets/vendor.js:19238:7
exports.default/<@http://localhost:3001/assets/vendor.js:17808:1
resolve@http://localhost:3001/assets/vendor.js:43760:12
_callee$@http://localhost:3001/assets/client.js:647:1
tryCatch@http://localhost:3001/assets/vendor.js:16521:37
invoke@http://localhost:3001/assets/vendor.js:16812:22
defineIteratorMethods/</prototype[method]@http://localhost:3001/assets/vendor.js:16573:16
tryCatch@http://localhost:3001/assets/vendor.js:16521:37
invoke@http://localhost:3001/assets/vendor.js:16754:24
defineIteratorMethods/</prototype[method]@http://localhost:3001/assets/vendor.js:16573:16
step@http://localhost:3001/assets/client.js:757:183
_asyncToGenerator/</<@http://localhost:3001/assets/client.js:757:437
Promise@http://localhost:3001/assets/vendor.js:21291:7
_asyncToGenerator/<@http://localhost:3001/assets/client.js:757:99
onLocationChange@http://localhost:3001/assets/client.js:749:12
[327]@http://localhost:3001/assets/client.js:858:1
__webpack_require__@http://localhost:3001/assets/vendor.js:692:1
hotCreateRequire/fn@http://localhost:3001/assets/vendor.js:111:20
[848]@http://localhost:3001/assets/client.js:3857:18
__webpack_require__@http://localhost:3001/assets/vendor.js:692:1
webpackJsonpCallback@http://localhost:3001/assets/vendor.js:24:23
@http://localhost:3001/assets/client.js:1:1
 vendor.js:19164:11

**Comment by ulani** [comment]
@madsithlord   thank you very much for crating this issue! Unfortunately, we have close it due to inactivity. Feel free to re-open it or [join](https://discord.com/invite/2nKEnKq) our [Discord](https://discord.com/invite/2nKEnKq) channel for [discussion](https://github.com/kriasoft/react-starter-kit/discussions/1950).

NOTE: The `main` branch has been updated with React Starter Kit v2, using JAM-style architecture.
